#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase

foamCleanPolyMesh -region air
foamCleanPolyMesh -region buildings
foamCleanPolyMesh -region vegetation

rm -f constant/air/F*
rm -f constant/air/constructMap*
rm -f constant/air/finalAgglom*
rm -f constant/air/globalFaceFaces*
rm -f constant/air/subMap*
rm -f constant/air/skyViewCoeff*
rm -f constant/air/sunViewCoeff*
rm -f constant/air/sunskyMap*
rm -f constant/air/sunVisibleOrNot*
rm -f constant/air/divqrsw*
rm -f constant/air/LAI*
rm -f constant/air/qrsw*

rm -f constant/vegetation/F*
rm -f constant/vegetation/constructMap*
rm -f constant/vegetation/finalAgglom*
rm -f constant/vegetation/globalFaceFaces*
rm -f constant/vegetation/subMap*
rm -f constant/vegetation/skyViewCoeff*
rm -f constant/vegetation/sunViewCoeff*
rm -f constant/vegetation/sunskyMap*
rm -f constant/vegetation/sunVisibleOrNot*
rm -f constant/vegetation/divqrsw*
rm -f constant/vegetation/LAI*
rm -f constant/vegetation/kcLAIboundary*
rm -f constant/vegetation/qrsw*

rm -rf constant/vegetation/polyMesh
rm -f constant/vegetation/cellToRegion*

rm -f 0/air/viewFactorField*
rm -f 0/air/LAD*
rm -rf 0/vegetation/

rm -f 0/*.gz

rm -rf ./constant/extendedFeatureEdgeMesh
rm -f ./constant/triSurface/*.eMesh*

# ----------------------------------------------------------------- end-of-file
