#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

blockMesh > log.blockMesh 2>&1
surfaceFeatures > log.surfaceFeatures 2>&1

echo "Creating mesh for air region"
cp -r constant/polyMesh constant/polyMesh.bckp
cp system/snappyHexMeshDict.air system/snappyHexMeshDict
snappyHexMesh -overwrite > log.snappyHexMesh.air 2>&1
rm -rf constant/air/polyMesh
mv constant/polyMesh constant/air/
changeDictionary -region air > log.changeDictionary.air 2>&1

echo "Creating mesh for vegetation region"
cp -r constant/polyMesh.bckp constant/polyMesh
cp system/snappyHexMeshDict.veg system/snappyHexMeshDict
snappyHexMesh -overwrite > log.snappyHexMesh.veg 2>&1
rm -rf constant/vegetation/polyMesh
mv constant/polyMesh constant/vegetation/
createPatch -region vegetation -overwrite > log.createPatch.veg 2>&1
changeDictionary -region vegetation > log.changeDictionary.veg 2>&1
cp -r 0/vegetation.bckp 0/vegetation
rm -rf constant/polyMesh.bckp

echo "Creating mesh for solid regions"
for i in buildings
do
    extrudeMesh > log.extrudeMesh.$i 2>&1
    rm -rf constant/$i/polyMesh
    mv constant/polyMesh constant/$i/
    createPatch -region $i -overwrite > log.createPatch.$i 2>&1
    changeDictionary -region $i > log.changeDictionary.$i 2>&1
    setSet -region $i -noVTK -batch system/$i/setset.batch > log.setSet.$i 2>&1
done

echo "Setting LAD values"
topoSet -region air > log.topoSet.air 2>&1
cp 0/air.bckp/LAD 0/air/.
setFields -region air > log.setFields.air 2>&1

# ----------------------------------------------------------------- end-of-file
